
pub const FIRST_NAMES: [&str; 20] = [
    "Bob",
    "Carla",
    "Wendy",
    "Troy",
    "Fiddly",
    "Giancarlo",
    "Nadia",
    "Rachel",
    "Hubert",
    "Bongo",
    "Cordelia",
    "Sha'nya",
    "Jamal",
    "Sven",
    "Arturo",
    "Gordon",
    "Adi",
    "Bolero",
    "Corky",
    "Vanderbilt",
];

pub const LAST_NAMES: [&str; 20] = [
    "Cheesebread",
    "Vanderbilt",
    "Flounders",
    "Scuff",
    "Carpacian",
    "Bombay",
    "Smith",
    "Cornbread",
    "Chi",
    "Suarez",
    "Wang",
    "Ivanov",
    "Bjornsson",
    "Wafflelouse",
    "Toulouse",
    "Bonaparte",
    "Scamdinger",
    "Œuf",
    "Sausige",
    "Pepperoni",
];

pub const QUIRKS: [&str; 41] = [
    "Shady",
    "Loud",
    "Aggressive",
    "Nervous",
    "Shy",
    "Squeamish",
    "Hostile",
    "Ingratiating",
    "Annoying",
    "Bored",
    "Scared",
    "Panicked",
    "Sketchy",
    "Mumbling",
    "Shaking",
    "Shifty",
    "Skittish",
    "Obtuse",
    "Irate",
    "Beguiling",
    "Clumsy",
    "Scheming",
    "Pompous",
    "Garlic Breath",
    "Sweating",
    "Sleepy",
    "Secretive",
    "Seductive",
    "Cryptic",
    "Confused",
    "Impatient",
    "Calm",
    "Condescending",
    "Bossy",
    "Murderous",
    "Undead",
    "Proselytizing",
    "Preachy",
    "Wacky",
    "Obessed with pasta",
    "Obsessed with bananas",
];

pub const SECRETS: [&str; 6] = [
    "Assassin",
    "Smuggler",
    "Fugitive",
    "Vampire",
    "Republican",
    "Taylor Swift fan",
];
