
pub const FIRST_NAMES: [&str; 15] = [
    "Bob",
    "Carla",
    "Wendy",
    "Troy",
    "Fiddly",
    "Giancarlo",
    "Nadia",
    "Rachel",
    "Hubert",
    "Bongo",
    "Cordelia",
    "Sha'nya",
    "Arturo",
    "Gordon",
    "Adi",
];

pub const LAST_NAMES: [&str; 16] = [
    "Cheesebread",
    "Flounders",
    "Scuff",
    "Carpacian",
    "Bombay",
    "Smith",
    "Cornbread",
    "Chi",
    "Suarez",
    "Wang",
    "Ivanov",
    "Bjornsson",
    "Wafflelouse",
    "Toulouse",
    "Bonaparte",
    "Scamdinger",
];

pub const QUIRKS: [&str; 33] = [
    "Shady",
    "Loud",
    "Aggressive",
    "Nervous",
    "Shy",
    "Squeamish",
    "Hostile",
    "Ingratiating",
    "Annoying",
    "Bored",
    "Scared",
    "Panicked",
    "Sketchy",
    "Mumbling",
    "Shaking",
    "Shifty",
    "Skittish",
    "Obtuse",
    "Irate",
    "Beguiling",
    "Clumsy",
    "Scheming",
    "Pompous",
    "Garlic Breath",
    "Sweating",
    "Sleepy",
    "Secretive",
    "Seductive",
    "Cryptic",
    "Confused",
    "Impatient",
    "Calm",
    "Condescending",
];

pub const SECRETS: [&str; 3] = [
    "Assassin",
    "Smuggler",
    "Fugitive"
];
